### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by jcazevedo** [jcazevedo/pawned#1]
Define and implement the layout for the whole application.

**Comment by maharifu** [comment]
Against Saleiro's will, I'll take this one. But everyone should have their saying about this. :p

**Comment by jcazevedo** [comment]
Some food for thought: http://builtwithbootstrap.com/.

**Comment by saleiro** [comment]
Someone called Maharifu shouldn't pickup this one...

**Comment by maharifu** [comment]
I just want to bootstrap it, then you'll take it. (see what I just did there...?) :p

**Comment by maharifu** [comment]
I'm closing this one. The basic layout is ready. The workflows for each component (tournaments, rounds, duels) are working; any enhancement to those should be considered in a new 'enhancement' issue.
