### ISSUE TITLE
Tournament Standings Chart

### ISSUE THREAD

**Issue by maharifu** [jcazevedo/pawned#15]
We should have a chart in the tournament view that shows the evolution of the standings of each player.

**Comment by jcazevedo** [comment]
It would be nice if we could customize this to allow adding and removing the lines in the chart of every player in the tournament.

**Comment by maharifu** [comment]
Isn't this the predefined behaviour of highchart? It already works that way in the ranking chart of the dashboard.

**Comment by jcazevedo** [comment]
OH. Yes, it is. I wasn't aware of that. :)

**Comment by maharifu** [comment]
Before before due time.
