### ISSUE TITLE
CRUD Duel

### ISSUE THREAD

**Issue by jcazevedo** [jcazevedo/pawned#16]
Implement the CRUD operations for the Duel model.

**Comment by jcazevedo** [comment]
We need to think about what the workflow of creating a duel is. Currently, it is not mandatory to create the matches the duel is associated with. In my opinion, once you create a duel, you should be prompted for the number of matches it is comprised of and have access to a form where you would specify the details for the duel and each match.

**Comment by maharifu** [comment]
As we don't have auto-pairings yet, the way it is now is useful; you can create duels (pairings) and add the results later.

I think this is what we need for this release. I'm closing this one.
