### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by jcazevedo** [jcazevedo/pawned#2]
Implement the authentication system for the application, considering a simple user + password solution.

**Comment by jcazevedo** [comment]
Consider using devise: https://github.com/plataformatec/devise.

**Comment by punnie** [comment]
I will.

**Comment by punnie** [comment]
I suppose this includes taking care of the first steps of the Authorization step as well. Should I prepare cancan?

**Comment by jcazevedo** [comment]
I forgot about permissions. I think they belong in a different issue. I'm opening it.

**Comment by jcazevedo** [comment]
Created a [separate issue](https://github.com/jcazevedo/pawned/issues/8) for permissions.

**Comment by punnie** [comment]
This is done for the moment. Sure some things will have to be changed along the ride, but the functionality is there. This one I think I'll close.

**Comment by jcazevedo** [comment]
I removed the email confirmation to ease the testing process, but opened an issue for us not to forget about it (#12).
