### ISSUE TITLE
Should the Duel model have a match_num?

### ISSUE THREAD

**Issue by maharifu** [jcazevedo/pawned#26]
If a duel is part of a tournament, than match_num is already in tournament.matches_per_duel.

If it is not a part of a tournament, then I think we should be able to add matches to a duel, instead of predefining how many matches we will want in that duel.

My opinion is we should keep it as an input in the duel form (if the duel is not a part of a round), but just use it to create the initial matches and not store it in the DB as an attribute of a duel.

Discuss... :p

**Comment by punnie** [comment]
IMHO, a match number should be requested when _creating_ a duel as a convenience to aid the creation of the necessary matches, but I see no reason to store it in the database.

So basically, I agree.

**Comment by jcazevedo** [comment]
I also agree.

**Comment by jcazevedo** [comment]
This is already handled. I'm closing it.
