### ISSUE TITLE
update_ratings

### ISSUE THREAD

**Issue by maharifu** [jcazevedo/pawned#27]
As matches can now be created without a date set, I changed the update_ratings method in match model. @jcazevedo please check this doesn't break the ratings calcs.

**Comment by jcazevedo** [comment]
I'm going to have a look at this later today. The matches should have a date set at least when a result is set. Is it going to be possible for them to have a result set and not a date?

**Comment by maharifu** [comment]
No, I guess not. It's just that when creating a duel, its matches are automatically created without date and result.
