### ISSUE TITLE
CRUD Player

### ISSUE THREAD

**Issue by jcazevedo** [jcazevedo/pawned#3]
Implement the CRUD operations for the Player model, which are the application users.

**Comment by punnie** [comment]
I'll take this. Should we call it User or Player?

**Comment by jcazevedo** [comment]
I think we should call it player, because we'll be allowing administrators to create them. Hence, it makes more sense to me them being Players than Users.

**Comment by punnie** [comment]
Looks good to me.

**Comment by punnie** [comment]
I've put this in /admin/players. Any remarks or objections?

**Comment by punnie** [comment]
For the moment this one is done. I'm sure we'll end up changing most of it, but the CRUD is working. I won't close this one for now.
