### ISSUE TITLE
Remove players from matches

### ISSUE THREAD

**Issue by maharifu** [jcazevedo/pawned#30]
There will be no standalone matches, as everything must be part of a duel. As such, it makes no sense to have  players in both models.

I guess this has a major impact on ratings, so we should thread carefully...

**Comment by jcazevedo** [comment]
I don't think we should remove the player relationships from matches. They provide a straightforward way to identify the black and white player and removing them would have some implications for that identification, namely:
- We would need to keep an order number for a match within a duel.
- We would need to make assumptions about the black/white alternation in matches within a duel.

In short, I think it will only complicate things. So, even though it might be redundant, I think the Match model should keep the relationships to the Player model.

**Comment by maharifu** [comment]
We could have a simple boolean field in the Duel model to figure out the white and black player, it wouldn't actually complicate much in terms of code.

However, we would need to query two tables instead of one to figure out the players in a match. On the other hand, we are doing just that right now, as the results of a match are somewhat meaningless without the duel results.

The only exception (match results matter by themselves) is when computing ratings, but that happens at match insertion, so you already have the players in memory, which should trigger no additional DB query.

**Comment by jcazevedo** [comment]
OK. I agree with that.

**Comment by maharifu** [comment]
And I'll take it. I'll try to keep everything from breaking apart. :p

**Comment by maharifu** [comment]
This is already done.
