### ISSUE TITLE
Matches should have a time

### ISSUE THREAD

**Issue by jcazevedo** [jcazevedo/pawned#34]
Matches should have a time. Otherwise it's impossible to define a logical sequence between them.

**Comment by jcazevedo** [comment]
The model is already prepared to have a time, so it's just a matter of fixing the user interface.

**Comment by maharifu** [comment]
Sorry, I caused this with be89275b164b8e88dbee85f7b4b939972368e490

**Comment by maharifu** [comment]
Fixed by f681eb77db058aadcf99eeb3c7a3faad1c5d0cc3.
