### ISSUE TITLE
Editing a match isn't clear

### ISSUE THREAD

**Issue by jcazevedo** [jcazevedo/pawned#35]
When editing a match, it isn't clear who's playing white and who's playing black.

**Comment by maharifu** [comment]
Can we move this to 12.05?

**Comment by jcazevedo** [comment]
We could, but it's something easy to do. I'll take it.

**Comment by jcazevedo** [comment]
Fixed this by including a disabled input tag with the white and black players that change when the reverse positions checkbox is changed. Using unicode pawns for labels. Code in 8f87b3d95ba5df3eb5f92bbad6b72122f1d582c7.
