### ISSUE TITLE
CRUD Match

### ISSUE THREAD

**Issue by jcazevedo** [jcazevedo/pawned#4]
Implement the CRUD operations for the Match model.

**Comment by saleiro** [comment]
I'll take this.

**Comment by jcazevedo** [comment]
I made some modifications to the Match model and some of the associated forms:
- Redefined the relationships to the Player model for their names to become clearer: 3df3e5481b052d04047476653d24bd057debfad8
- Added simple_form associations in the new and edit forms to show a select tag for the player selection: bcebd309695747407a5cd5bde2b36daae4ef5f83
- Added a virtual attribute result to the model to abstract the usage of white_result and black_result fields: 2e2340e9818f0b597a84deb710b35b0f005b68e6

**Comment by jcazevedo** [comment]
Even though this needs to be integrated with the Duel model, I'm closing it for now.
