### ISSUE TITLE
CRUD Tournament and Rounds

### ISSUE THREAD

**Issue by jcazevedo** [jcazevedo/pawned#5]
Implement the CRUD operations for the Tournament and Round models.

**Comment by saleiro** [comment]
and this one.

**Comment by maharifu** [comment]
This has to include a Tiebreaker model. Should it be in a separate issue?

**Comment by jcazevedo** [comment]
I think we shouldn't include the Tiebreaker model for this milestone, yet. If necessary, we can open a separate issue for that later.

**Comment by maharifu** [comment]
But the problem is that if you create a tournament now and there is a tie, you'll need some way to solve it.

**Comment by saleiro** [comment]
For release 12.04 we are going to use the same framework as we were using until now. Therefore the ranking on each round should be manually updated.

**Comment by jcazevedo** [comment]
Yeah. You solve the ties by hand. :)

**Comment by maharifu** [comment]
Yes, but how? Do we introduce a Standings model to tell where everyone is on the tournament?

My understanding is that we could have a Tiebreaker model that would be filled by hand for 12.03 and automatic by 12.05 :p

**Comment by jcazevedo** [comment]
You're right. We should have a Standings model to associate with each round, even if we have a Tiebreaker model.

**Comment by jcazevedo** [comment]
Created an [issue](https://github.com/jcazevedo/pawned/issues/9) for that.

**Comment by maharifu** [comment]
I think this is ready for this release. I'm closing this one for now.
