### ISSUE TITLE
Rankings

### ISSUE THREAD

**Issue by jcazevedo** [jcazevedo/pawned#6]
Implement the methods to support the rankings of players.

**Comment by jcazevedo** [comment]
CRMS (the system we're using at http://fcc.jcazevedo.net/) is using [the USCF rating system](http://math.bu.edu/people/mg/ratings/rs/rs2.html).

**Comment by jcazevedo** [comment]
Anyone opposes against using [flot](http://code.google.com/p/flot/) for the graphs?

**Comment by jcazevedo** [comment]
I'll take this.

**Comment by jcazevedo** [comment]
I ended up opting for [Highcharts](http://www.highcharts.com/) for plots.

**Comment by punnie** [comment]
![noooooooooo!](http://nooooooooooooooo.com/vader.jpg)

**Comment by jcazevedo** [comment]
Why? They look kind of nice:

![highcharts](http://jcazevedo.net/contents/graph.png)

**Comment by punnie** [comment]
Disregard that. Just wanted to reply with a dramatic image.

**Comment by punnie** [comment]
Just to clear things up:
- Rating: the current absolute score of a player
- Ranking: the score of a player relative to other players (if he's first, second, whatever).

**Comment by jcazevedo** [comment]
Yes. As is it currently implemented, the Ranking will be obtained by a list of Ratings.

**Comment by jcazevedo** [comment]
Implemented the live rankings on the dashboard and supplied a method to obtain the live rankings from a given date in time.

I'm closing this. If problems are found on the rating calculation, please file them as bugs in a separate issue.
