### ISSUE TITLE
Integrate with twitter bootstrap

### ISSUE THREAD

**Issue by jcazevedo** [jcazevedo/pawned#7]
Take into account that some of the rails stuff (such as forms), might not integrate very well out of the box with twitter bootstrap.

**Comment by jcazevedo** [comment]
I'll take this and probably use [simple_form](https://github.com/plataformatec/simple_form).

**Comment by punnie** [comment]
Boy, will you have fun with the forms Devise generates..

**Comment by jcazevedo** [comment]
Did an initial integration with twitter bootstrap using [simple_form](https://github.com/plataformatec/simple_form). It is likely that some styles still need to be tuned, but the initial scaffold is in. Refer to the Players' CRUD for an example of how to use simple_form:

```
<%= simple_form_for([:admin, @player], :html => {:class => 'form-horizontal'}) do |f| %>
  <legend>Player</legend>

  <% if f.error_notification %>
    <%= f.error_notification %>
  <% end %>

  <%= f.input :name %>
  <%= f.input :email, :as => :email %>
  <%= f.input :password %>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
    <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger" %>
  </div>
<% end %>
```

I'm closing this.
