### ISSUE TITLE
Standings model

### ISSUE THREAD

**Issue by jcazevedo** [jcazevedo/pawned#9]
Implement the Standings model to be associated with each round.

**Comment by saleiro** [comment]
It should be able to support different models. For 12.03 it will be the mode "Teixeira_inserts".

**Comment by jcazevedo** [comment]
No. This should be a generic standings model (i.e. relative positions of players in a given round). The different models that we ought to support are the different tournament types, but that is another concern.

**Comment by saleiro** [comment]
And what about the different score parameters which are model dependent?

**Comment by punnie** [comment]
Just figuring it out: this will just be a table with a player_id, a round_id and a position?

**Comment by saleiro** [comment]
It should also have a model-dependent scores, such as points, BuT, xyz, which define  the position on each round.

**Comment by jcazevedo** [comment]
And eventually a score. The way to set this stuff is dependent on the to-be-implemented tournament type model.

**Comment by punnie** [comment]
Do we really need to store everything in the database? Recalculating everything in case someone inserts a ranked game before the tourney will be a gargantuan pain in the ass.

**Comment by jcazevedo** [comment]
Inserting a ranked game before a tourney would potentially affect the tournament pairings, and since we're not going to change them, the standings won't change.

**Comment by saleiro** [comment]
The round standings will be calculated once, when a round is considered "closed". We can also disable the ranked games during tournaments.

**Comment by punnie** [comment]
I was just wondering if there is any value you want to store in the tournament standings that is affected by a un-added previous game, such as anything a Tiebreaker would use.

**Comment by maharifu** [comment]
I think that as soon as a tournament starts, anything that is not tournament related should _not_ affect the tournament in any way (not even a dead player. that still counts as forfeit).

**Comment by jcazevedo** [comment]
That seems a weird case. In any case, the Standings model should refer to closed standings. The logic to calculate them is in the tournament type model, therefore making it off-topic for this issue.

**Comment by jcazevedo** [comment]
It is possible to create and edit the standings for a given round. We still have to think about the layout of things, but I'm referring to #1 for that.
